/* Generated By:JJTree: Do not edit this line. ASTAssingVariableCmd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssingVariableCmd extends SimpleNode {
  public ASTAssingVariableCmd(int id) {
    super(id);
  }

  public ASTAssingVariableCmd(Caesar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e3f9af2beecff00e6c28bda41f001136 (do not edit this line) */
