/* Generated By:JJTree: Do not edit this line. ASTAssignVariableCmd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package caesar;

public
class ASTAssignVariableCmd extends SimpleNode {
  public ASTAssignVariableCmd(int id) {
    super(id);
  }

  public ASTAssignVariableCmd(Caesar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CaesarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cd0396c5ee71c240450805adf88b3cf0 (do not edit this line) */
