/* Generated By:JJTree: Do not edit this line. ASTCreateVariableCmd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package caesar;

public
class ASTCreateVariableCmd extends SimpleNode {
  public ASTCreateVariableCmd(int id) {
    super(id);
  }

  public ASTCreateVariableCmd(Caesar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CaesarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=99a8150f53d06091cfbe21d74d02de69 (do not edit this line) */
