/* Generated By:JJTree: Do not edit this line. ASTPrintlnCmd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package caesar;

public
class ASTPrintlnCmd extends SimpleNode {
  public ASTPrintlnCmd(int id) {
    super(id);
  }

  public ASTPrintlnCmd(Caesar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CaesarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c025cec920d4b02cc1384a7bb4cde40d (do not edit this line) */
