/* Generated By:JJTree: Do not edit this line. ASTWhileCmd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package caesar;

public
class ASTWhileCmd extends SimpleNode {
  public ASTWhileCmd(int id) {
    super(id);
  }

  public ASTWhileCmd(Caesar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CaesarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7245887b4f1dd340542bbb5576297f2f (do not edit this line) */
