/* Generated By:JavaCC: Do not edit this line. CaesarVisitor.java Version 5.0 */
package caesar;

public interface CaesarVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTCommandList node, Object data);
  public Object visit(ASTCommand node, Object data);
  public Object visit(ASTCreateVariableCmd node, Object data);
  public Object visit(ASTAssignVariableCmd node, Object data);
  public Object visit(ASTIfCmd node, Object data);
  public Object visit(ASTElsePart node, Object data);
  public Object visit(ASTCondition node, Object data);
  public Object visit(ASTRelationalOperator node, Object data);
  public Object visit(ASTWhileCmd node, Object data);
  public Object visit(ASTPrintlnCmd node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTExpressionX node, Object data);
  public Object visit(ASTTerm node, Object data);
  public Object visit(ASTTermX node, Object data);
  public Object visit(ASTFactor node, Object data);
  public Object visit(ASTFactorRest node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTIntConst node, Object data);
  public Object visit(ASTRealConst node, Object data);
}
/* JavaCC - OriginalChecksum=57b9e5d5a082b10edfa6bc9fa576f074 (do not edit this line) */
