/* Generated By:JavaCC: Do not edit this line. CaesarTreeConstants.java Version 5.0 */
package caesar;

public interface CaesarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCOMMANDLIST = 1;
  public int JJTCOMMAND = 2;
  public int JJTCREATEVARIABLECMD = 3;
  public int JJTASSIGNVARIABLECMD = 4;
  public int JJTIFCMD = 5;
  public int JJTELSEPART = 6;
  public int JJTCONDITION = 7;
  public int JJTRELATIONALOPERATOR = 8;
  public int JJTWHILECMD = 9;
  public int JJTPRINTLNCMD = 10;
  public int JJTEXPRESSION = 11;
  public int JJTEXPRESSIONX = 12;
  public int JJTTERM = 13;
  public int JJTTERMX = 14;
  public int JJTFACTOR = 15;
  public int JJTFACTORREST = 16;
  public int JJTIDENTIFIER = 17;
  public int JJTINTCONST = 18;
  public int JJTREALCONST = 19;


  public String[] jjtNodeName = {
    "Start",
    "CommandList",
    "Command",
    "CreateVariableCmd",
    "AssignVariableCmd",
    "IfCmd",
    "ElsePart",
    "Condition",
    "RelationalOperator",
    "WhileCmd",
    "PrintlnCmd",
    "Expression",
    "ExpressionX",
    "Term",
    "TermX",
    "Factor",
    "FactorRest",
    "Identifier",
    "IntConst",
    "RealConst",
  };
}
/* JavaCC - OriginalChecksum=a0623354ba81e9f7980d31677a14ea5b (do not edit this line) */
