/* Generated By:JJTree&JavaCC: Do not edit this line. CaesarConstants.java */
package caesar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CaesarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 1;
  /** RegularExpression Id. */
  int ENDPROGRAM = 2;
  /** RegularExpression Id. */
  int VAR = 3;
  /** RegularExpression Id. */
  int ARRAY = 4;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int ELSE = 6;
  /** RegularExpression Id. */
  int ENDIF = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int ENDWHILE = 9;
  /** RegularExpression Id. */
  int FOR = 10;
  /** RegularExpression Id. */
  int IN = 11;
  /** RegularExpression Id. */
  int TO = 12;
  /** RegularExpression Id. */
  int ENDFOR = 13;
  /** RegularExpression Id. */
  int PRINTLN = 14;
  /** RegularExpression Id. */
  int COLON = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int IDENT = 17;
  /** RegularExpression Id. */
  int ASSIGN = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int MINUS = 20;
  /** RegularExpression Id. */
  int MULTIPLY = 21;
  /** RegularExpression Id. */
  int DIVIDE = 22;
  /** RegularExpression Id. */
  int LBRC = 23;
  /** RegularExpression Id. */
  int RBRC = 24;
  /** RegularExpression Id. */
  int LABRC = 25;
  /** RegularExpression Id. */
  int RABRC = 26;
  /** RegularExpression Id. */
  int EQ = 27;
  /** RegularExpression Id. */
  int NE = 28;
  /** RegularExpression Id. */
  int LT = 29;
  /** RegularExpression Id. */
  int GT = 30;
  /** RegularExpression Id. */
  int LE = 31;
  /** RegularExpression Id. */
  int GE = 32;
  /** RegularExpression Id. */
  int DOT = 33;
  /** RegularExpression Id. */
  int REAL_CONST = 34;
  /** RegularExpression Id. */
  int INT_CONST = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;
  /** RegularExpression Id. */
  int LETTER = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"program\"",
    "\"endprogram\"",
    "\"var\"",
    "\"array\"",
    "\"if\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"endwhile\"",
    "\"for\"",
    "\"in\"",
    "\"..\"",
    "\"endfor\"",
    "\"println\"",
    "\":\"",
    "\",\"",
    "<IDENT>",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\".\"",
    "<REAL_CONST>",
    "<INT_CONST>",
    "<DIGIT>",
    "<LETTER>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
  };

}
